### ISSUE TITLE
Follow Imports: absolute, relative, and directories (not just modules)

### ISSUE THREAD

**Issue by aguthrie19** [thebjorn/pydeps#35]
How can pydeps display dependencies between files in a directory nested with/without modules?
Previous issues [https://github.com/thebjorn/pydeps/issues/25](https://github.com/thebjorn/pydeps/issues/25) or [https://github.com/thebjorn/pydeps/issues/28](https://github.com/thebjorn/pydeps/issues/28) don't quite answer this question.

For example, I'd like to display the dependencies of my project under the following "directory_root":
```
directory_root
├── module_a
│   ├── __init__.py
│   ├── a.py
│   └── b.py
├── directory_a
│   ├── c.py
│   └── d.py
└── module_b
     ├── __init__.py
     ├── e.py
     └── f.py
```
where the dependencies include python libraries, modules inside this directory_root, and even files in this directory_root not organized as modules (like c.py or d.py)

**Comment by thebjorn** [comment]
Hi Alexander and thank you for your interest in pydeps.  Pydeps uses a custom version of the standard library `modulefinder.py` to find imports, and it does this by looking at the import op-codes (i.e. what Python is compiled to, think .pyc files). If you can't (or don't) import a module then pydeps doesn't see it. #25 didn't import the modules and #28 couldn't (because of a syntax error). I don't think there is any workaround for this behavior other than to organize your code as proper modules...

**Comment by aguthrie19** [comment]
I see. I'll restructure my code so that all modules (and dependencies) are visible to pydeps.
To do this, if I understand correctly, I just need to add `__init__.py` files containing `from . import *` at each directory? (this way [imp.find_module](https://docs.python.org/3/library/imp.html#imp.find_module) used by [`MyModuleFinder(mf27.ModuleFinder)`](https://github.com/thebjorn/pydeps/blob/master/pydeps/py2depgraph.py#L81) ) is aware of each submodule?

So my new "directory_root" would look like? :
```
directory_root
├── module_a
│   ├── __init__.py
│   ├── a.py
│   └── b.py
├── directory_a
│   ├── __init__.py
│   ├── c.py
│   └── d.py
└── module_b
     ├── __init__.py
     ├── e.py
     └── f.py
```
Thank you Bjorn

**Comment by thebjorn** [comment]
You're correct, except for the `from . import *` part (it doesn't do what you think it does).

E.g., the following directory contents (see note about yamldirs command under "New in version 1.1.7" at https://github.com/datakortet/yamldirs):
```
(dev) go|c:\srv\tmp> yamldirs pydepsstar
pydepsstar:
  a:
    a.py: ''
    a2.py: ''
    __init__.py: from . import *
  b:
    b.py: ''
    __init__.py: from . import *
  __init__.py: from . import *
```
produces:
![image](https://user-images.githubusercontent.com/1193143/67148957-d0e98000-f2a5-11e9-86b8-b37dce02772e.png)
while changing the top-level `__init__.py` file to explicitly include the sub-modules, i.e.:
```
(dev) go|c:\srv\tmp> yamldirs pydepsstar
pydepsstar:
  a:
    a.py: ''
    a2.py: ''
    __init__.py: from . import *
  b:
    b.py: ''
    __init__.py: from . import *
  __init__.py: from . import a, b
```
produces
![image](https://user-images.githubusercontent.com/1193143/67148980-13ab5800-f2a6-11e9-9ddd-e34ee4d9205c.png)
