### ISSUE TITLE
Draw module internal dependencies

### ISSUE THREAD

**Issue by afischer-opentext-com** [thebjorn/pydeps#42]
Hi, 

my question somewhat relates to issue #25. 

First, I encounter the same issue as outlined in that ticket. It got closed without addressing the issue unfortunately. The workaround mentioned there correctly works in the way that the python files become part of the output. 

But the workaround does not work in case a modules file imports another file from the same module. 

Given 
```(dev) go|c:\srv\tmp> tree mydir
mydir
|   `-- __init__.py
|   `-- controller.py
|   `-- database.py
|   `-- exceptions.py
|   `-- mainclass.py
    `-- models.py
```
and `mydir.controller` imports and uses `mydir.database`, then this dependency is not available in the graph. 

Is there any way to make this dependency visible? I would like to use that information as it would ease refactoring / organizing code as it would greatly make internal oddities visible. 

Kind regards
alex

**Comment by thebjorn** [comment]
Hi Alexander, and thank you for your interest in pydeps.

I'm not sure I understand what you mean when you say:

> and mydir.controller imports and uses mydir.database, then this dependency is not available in the graph.

Given the following project (the yamldirs command is from the https://pypi.org/project/yamldirs/ project, and packages up a directory into a yaml format -- sort of like `tree` but with contents):
```
(dev) go|c:\srv\tmp\issue42> yamldirs mydir
mydir:
  models.py: from . import exceptions
  __init__.py: from . import mainclass
  controller.py: from . import database, exceptions
  database.py: from . import exceptions
  exceptions.py: ''
  mainclass.py: from . import models, controller
```
where only `mainclass.py` is imported into `__init__.py`, but where the modules are "strongly connected", i.e. all modules are imported by some other module, and there is an import path from any module to `__init__.py`.  Running pydeps:

    (dev) go|c:\srv\tmp\issue42> pydeps mydir

produces:
![mydir](https://user-images.githubusercontent.com/1193143/68935411-e06ec280-0798-11ea-9351-209a03e3dca1.png)

**Comment by afischer-opentext-com** [comment]
Ah, thanks for the quick reply! You understood me fully correctly. I see that this works with relative imports. The project I was testing with, uses absolute imports, even for files in the same module. I see if I can change that. Still, those absolute imports are not visible.

**Comment by rugg2** [comment]
I'm also interested in absolute imports being shown, to visualise the structure of a given module that's being worked on.

**Comment by thebjorn** [comment]
@rugg2 I can't reproduce this with the current version of pydeps (v1.9.3). Changing the code to use absolute imports:
```
(dev) go|c:\srv\tmp\issue42> yamldirs mydir
mydir:
  models.py: from mydir import exceptions
  __init__.py: from mydir import mainclass
  controller.py: from mydir import database, exceptions
  database.py: from mydir import exceptions
  exceptions.py: ''
  mainclass.py: from mydir import models, controller
```
I still get the same graph. I've set the `PYTHONPATH` to the `issue42` directory before running pydeps since there is no setup.py file here.
