### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by terwilliger42** [thebjorn/pydeps#94]
Hi @thebjorn - thanks for all of your hard work on this project!   Your tool is extremely helpful the work that I'm doing.  I am so grateful.  👍   

That said, I'm running into a little trouble.  I've simplified into a very basic testcase:
```
test:
  bar:
    __init__.py: print("imported bar")
  foo:
    __init__.py: |-
      import bar
      print("Imported foo")
  run_test.py: import foo
```

When I run this, I don't get a "bar" dependency from pydeps, even though it is being imported. 
```
$ cd test
$ ../py38/bin/python run_test.py
imported bar
Imported foo
$ 
../py38/bin/pydeps run_test.py 
```
Expect "bar" dependency on "foo"
<img width="107" alt="Screen Shot 2021-07-02 at 2 22 52 pm" src="https://user-images.githubusercontent.com/22688337/124329823-03521400-db41-11eb-8d40-01dd442ce5e8.png">

Any idea what the cause is?  Thanks again for all of your work on this project.
